Maths Doubled Score 10 DP1 = 
SUMX(
    VALUES('Assessment Results'[StudentId]),
    VAR Maths = CALCULATE(
        MAX('Assessment Results'[GradeValue]),
        'Assessment Results'[Subject] = "Maths",
        'Assessment Results'[YearGroup] = "10",
        'Assessment Results'[Term] = "Spring",
        'Assessment Results'[ResultDate] >= DATE(2024, 9, 1),
        'Assessment Results'[AssessmentType] = "1-9"
    )
    RETURN 
        IF(
            ISBLANK(Maths),
            BLANK(),
            Maths * 2
        )
)/[Year 10 Students]
