Students in PA = 
CALCULATE(
    DISTINCTCOUNT('AL Attendance OT'[ID]),
    FILTER(
        ALL('AL Attendance OT'[ID]),
        CALCULATE(
            AVERAGE('AL Attendance OT'[Attendance Count]),
            'AL Attendance OT'[Date] <= MAX('AL Attendance OT'[Date])
        ) < 0.9
    )
)/DISTINCTCOUNT('AL Attendance OT'[ID])
