Suspension % 2024-2025 = 
IF (
    SELECTEDVALUE('Anglian Learning Exclusions'[Academic Year]) = "2024/2025",
    DIVIDE(
        CALCULATE(
            'Anglian Learning Exclusions'[Suspension Events],
            'Anglian Learning Exclusions'[Academic Year] = "2024/2025"
        ),
        CALCULATE(
            DISTINCTCOUNT('Anglian Learning Students'[Student ID]),
            'Anglian Learning Students'[Status] = "Active"
        )
    )
)
